{"uuid": "981f8db2-a463-4ff2-937d-1a52a8a7992b", "children": ["973edd40-c294-4051-a30e-b7619c3676ea", "277d11f5-4452-47ea-abc9-e478bd9e50e6", "96d04f24-5a74-4046-8f03-362ecb4e7329"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'url' referenced before assignment\n", "trace": "  File \"C:\\Users\\fahadmuhammad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\fahadmuhammad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\fahadmuhammad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\fahadmuhammad\\Desktop\\Amazon\\conftest.py\", line 10, in driver\n    url = test_data.login[url]\n"}, "start": 1698169667491, "stop": 1698169667533}], "start": 1698169667491, "stop": 1698169667630}